version: '3'
services:
  rust_1:
    build: ./rust_1
    # ports:
    #   - "3000:3000"
    # links:
    #   - db
    networks:
      - local_network
  rust_2:
    build: ./rust_2
    # ports:
    #   - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
      - rust_1
    networks:
      - local_network  
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_pass"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - local_network
    volumes:
       - ./postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U test_user -d test_db'"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - local_network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - local_network 
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
        - local_network 
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1      
    networks:
        - local_network    
networks:
  local_network:
    driver: bridge         